library(neurobase)
library(parallel)

#FAST has already been run on the mprages--this code uses the CSF mask generated from FAST to calculate TBV


dirs = system(paste("find . -name FAST"),intern=TRUE) 

do.tbv = function(i){

#list all files generated by FAST
FAST = list.files(path = paste0(dirs[i]), recursive=TRUE,full.names=TRUE)

#Subset the list of all FAST imgs for the images that end with "_brain_seg.nii.gz"
FAST_TB_seg = FAST[which(grepl("*_brain_seg.nii.gz",FAST))]

df = data.frame()

for (j in 1:length(FAST_TB_seg)){
  #string split to pull labels from file path/name to use as colnames in DF
  labels=strsplit(FAST_TB_seg[j],"/")[[1]]
  Subj = labels[2]
  Site = labels[3]
  Scan = gsub("_brain_seg.nii.gz","",labels[6])  
  
  #Read in CSF,GM,WM segmented img (the "_brain_seg.nii.gz" img)
  seg_img = readnii(FAST_TB_seg[j])
  
  #Intensities: CSF = 1, GM = 2, WM =3
  #Create a binary CSF mask where CSF==0, and GM/WM==1
  CSF_mask = seg_img>1
 
  #read in mprage 
   mprage = readnii(paste0(dirname(dirs[i]),"/mass/",
                          Scan,"_brain.nii.gz"))
  
  # multiply CSF mask by mprage so only GM/WM vol. remains
  CSF_masked_brain = mprage*CSF_mask
  
  #Calculate TBV in mL
  Total_Brain =  CSF_masked_brain>0
  Total_Brain_Lab = table(Total_Brain[Total_Brain==1])
  vreslab = voxres(mprage,units = "cm")
  TBV = Total_Brain_Lab*vreslab
  
  #bind each TBV and info for each subj in one df
  all_together = cbind(Subj,Site,Scan,TBV)
  df = rbind(df, all_together)
  #rownames(df)=c()
  write.csv(df,paste0(dirname(dirs[i]),"/TBV.csv"))
  
  
}
#print(df)
}

i = c(1:35,37:41)
do.tbv(i)

